# Databricks notebook source
dbutils.widgets.text("catalog_name", "bfx-stg")
catalog_name = dbutils.widgets.get('catalog_name')

spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awff`.`Account`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awff`.`DepartmentGroup`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awff`.`Finance`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awff`.`ProductMapping`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awff`.`Scenario`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`Address`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`Customer`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`CustomerAddress`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`Product`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`ProductCategory`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`ProductDescription`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`ProductModel`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`ProductModelProductDescription`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`SalesOrderDetail`")
spark.sql("DROP TABLE IF EXISTS `" + catalog_name + "`.`awlt`.`SalesOrderHeader`")